# Generated by Django 5.2.3 on 2025-06-11 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_categoria', models.CharField(db_column='nome_categoria', max_length=70)),
                ('descricao', models.TextField(db_column='descricao')),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('nome_fornecedor', models.CharField(db_column='nome_fornecedor', max_length=70)),
                ('telefone', models.CharField(db_column='telefone', max_length=20)),
            ],
            options={
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('nome_produto', models.CharField(db_column='nome_produto', max_length=70)),
                ('marca', models.CharField(db_column='marca', max_length=70)),
                ('preco', models.FloatField(db_column='preco')),
                ('id_categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.DO_NOTHING, to='catalogo.categoria')),
            ],
            options={
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProdutoFornecedor',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('id_fornecedor', models.ForeignKey(db_column='id_fornecedor', on_delete=django.db.models.deletion.DO_NOTHING, to='catalogo.fornecedor')),
                ('id_produto', models.ForeignKey(db_column='id_produto', on_delete=django.db.models.deletion.DO_NOTHING, to='catalogo.produto')),
            ],
            options={
                'abstract': False,
                'managed': True,
            },
        ),
    ]
