# Generated by Django 5.2.3 on 2025-06-11 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='nome_produto',
        ),
        migrations.AddField(
            model_name='produto',
            name='descricao',
            field=models.CharField(db_column='descricao', default='sem descricao', max_length=70),
            preserve_default=False,
        ),
    ]
