# Generated by Django 5.2.3 on 2025-06-12 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_remove_categoria_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.CharField(db_column='imagem', default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nome_categoria',
            field=models.CharField(db_column='nome_categoria', default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='nome_fornecedor',
            field=models.CharField(db_column='nome_fornecedor', default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='telefone',
            field=models.CharField(db_column='telefone', default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.CharField(db_column='descricao', default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='produto',
            name='marca',
            field=models.CharField(db_column='marca', default='', max_length=70),
        ),
    ]
